- hosts: localhost
  vars:
    source_key: "./.ssh/id_ed25519"
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_ed25519"
    personal: "{{ lookup('env', 'HOME') }}"
  pre_tasks:
  - name: Update Apt
    become: true
    apt:
      force_apt_get: true
      update_cache: true
      state: present
  tasks:
    - import_tasks: tasks/ssh.yml
    - import_tasks: tasks/packages.yml
    - import_tasks: tasks/git-config.yml
    - import_tasks: tasks/zsh.yml
    - import_tasks: tasks/neovim.yml
    - import_tasks: tasks/dotfiles.yml
